### ISSUE TITLE
Error while sending request - 6d9cc25c-ea95-4e30-bc5e-ca424cc60475

### ISSUE THREAD

**Issue by js1251** [js1251/bspProtect-support#20]
An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_protection.BspProtection.BspProtector.<GetResponse>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_protection.BspProtection.BspProtector.<Protect>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_application.MVVM.ViewModel.ProtectionTab.RunViewModel.Process()
   at client_application.MVVM.ViewModel.BaseViewModel.ProcessHelper(Object sender, DoWorkEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by js1251** [comment]
Notably after a second try, the request was successful

**Comment by js1251** [comment]
Potentially fixed in 1.0.25
