### ISSUE TITLE
Response 500 - 51aa2748-e5b4-4551-9e4b-e58c4a93277f

### ISSUE THREAD

**Issue by js1251** [js1251/bspProtect-support#31]
Request failed.
HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
Stack Trace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at client_protection.BspProtection.BspProtector.<GetResponse>d__47.MoveNext()
   at client_protection.BspProtection.BspProtector.<GetResponse>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_protection.BspProtection.BspProtector.<Protect>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_application.MVVM.ViewModel.ProtectionTab.RunViewModel.Process()
   at client_application.MVVM.ViewModel.BaseViewModel.ProcessHelper(Object sender, DoWorkEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

An error occurred in the software. @js1251 will reach out to you soon. Updates will be posted here.

**Comment by js1251** [comment]
Potentially fixed in 1.0.25
