### ISSUE TITLE
nodraw missing serverside | 5981cd28-7c5d-48dc-9146-17ec9a7db315

### ISSUE THREAD

**Issue by js1251** [js1251/bspProtect-support#66]
An error occurred in the software. @js1251 will reach out to you soon. Updates will be posted here.

Request failed.
Exception: Internal Server Error while performing protection!
Stack Trace:    at client_protection.BspProtection.BspProtector.<GetResponse>d__47.MoveNext()
   at client_protection.BspProtection.BspProtector.<GetResponse>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_protection.BspProtection.BspProtector.<Protect>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at client_application.MVVM.ViewModel.ProtectionTab.RunViewModel.Process()
   at client_application.MVVM.ViewModel.BaseViewModel.ProcessHelper(Object sender, DoWorkEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by js1251** [comment]
Nodraw surfaceprop not present on server for some reason

**Comment by js1251** [comment]
Potentially related to having bsp / Hammer / related files open during protection

**Comment by js1251** [comment]
Suspected issue was: Users would use the manual bypass even before any surfaceprop extraction code was run, completely skipping the process, causing an empty list to be sent to the server, producing a failed protection request.

Fix pushed in 1.0.54

Still observing if it happens again due to other suspected cause of hammer / source game being open during protection, possibly disallowing read access for bspProtect
